config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # post 'pizzas/add_to_cart/:id', to: 'pizzas#add_to_cart', as: 'add_to_cart'
  # delete '/pizzas/remove_from_cart/:id', to: 'pizzas#remove_from_cart', as: 'remove_from_cart'

  resources :menu, only: [:index]
  # resources :pizzas
  resource  :carts, only: [:show]
  resources :orders, only: [:edit, :update]

  resources :order_items
  root 'home#index'
  get 'delivery', to: 'pizzas#delivery'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_total

  #validate data
  validates :name,
    presence: true,
    format: /[А-Яа-яЁё]/,
    length: { in: 3..40 },
    on: :update
  validates :phone,
    presence: true,
    format:  /(\+375)(29|25|44|33)(\d{3})(\d{2})(\d{2})/,
    length: { is: 13 },
    numericality: { only_integer: true },
    on: :update
  validates :street,
    presence: true,
    format: /[А-Яа-яЁё]/,
    length: { in: 3..100 },
    on: :update
  validates :house_number, :subway_number, :apartament_number,
    presence: true,
    numericality: { only_integer: true },
    on: :update

  # methods
  def total_price
    order_items.collect{ |order_item| set_order_price_item(order_item) }.sum
  end

  def set_order_price_item(order_item)
    order_item.valid? ? order_item.total_price : 0
  end

  private
    def set_total
      self[:total] = total_price
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :pizza

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      pizza.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

    def set_unit_price
      self[:unit_price] = unit_price
    end

    def set_total_price
      self[:total_price] = quantity * total_price
    end
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout false
  
  def index
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  helper_method :order_pizza_include?

  def index
    @pizzas = Pizza.all
    @order_item = OrderItem.new(order_id: session[:order_id])
    # byebug
    @order_items = OrderItem.where(order_id: session[:order_id]).select(:pizza_id, :order_id)
  end

  private

  def order_pizza_include?(pizza_id)
    @order_items.each do |item|
      if item.pizza_id == pizza_id
        return true
      end
    end
    return false
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order_item = OrderItem.create(order_item_params.merge(order_id: session[:order_id]))
    current_order.save(validate: false)
  end

  def update
    @order_item = OrderItem.find(params[:id])
    @order_item.update(order_item_params)
  end

  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy
  end

  private
    def order_item_params
      params.require(:order_item).permit(:pizza_id, :quantity)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper
  helper_method :order_total
  before_action :set_order, only: [:edit, :update]

  def edit
  end

  def update
    if @order.update(order_params)
      flash[:notice] = "Заказ успешно cформирован"
      set_confirmed_by
      send_order_to_telegram
      session.delete(:order_id)
      redirect_to root_path
    else
      render :edit, location: edit_order_path
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :phone, :street, :house_number, :subway_number, :apartament_number, :note)
  end

  def set_order
    @order = Order.find(params[:id])
  end

end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  # before_action :initialize_session
  # before_action :increment_visit_count, only: %i[index]
  # before_action :load_cart
  before_action :set_pizza, only: [:show, :update, :edit, :destroy]

  def show
  end

  def index
    @pizzas = Pizza.all
  end

  def new
    @pizza = Pizza.new
  end

  def create
    @pizza = Pizza.new(pizza_params)
    if @pizza.save
      flash[:notice] = "Pizza #{@pizza.name} создана"
      redirect_to pizza_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pizza.update(pizza_params)
      flash[:notice] = "Pizza #{@pizza.name} успешно обновлена"
      redirect_to pizza_path
    else
      render 'edit'
    end
  end

  def destroy
    @pizza.destroy
    flash[:notice] = "Пицца #{@pizza.name} успешно удалена"
    redirect_to pizza_path
  end

  # def add_to_cart
  #   id = params[:id].to_i
  #   session[:cart] << id unless session[:cart].include?(id)
  #   redirect_to root_path
  # end

  # def remove_from_cart
  #   id = params[:id].to_i
  #   session[:cart].delete(id)
  #   redirect_to root_path
  # end

  # def delivery
  # end

  private
  # Initializa the visin on first visit
  # def initialize_session
  #   session[:visit_count] ||= 0
  #   session[:cart] ||= []
  # end

  # def load_cart
  #   @cart = Pizza.find(session[:cart])
  # end

  # def increment_visit_count
  #   session[:visit_count] += 1
  #   @visit_count = session[:visit_count]
  # end
  def set_pizza
    @pizza = Pizza.find(params[:id])
  end

  def pizza_params
    params.require(:pizza).permit(:name, :price, :ingredients, :description, :weight, :photo, :popularity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      @order = Order.new
      @order.save(validate: false)
      session[:order_id] = @order.id
      @order
    end
  end

  def order_items_size
    OrderItem.where(order_id: session[:order_id]).size
  end

  def cart_items
    OrderItem.where(order_id: session[:order_id]).order(:created_at)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  require 'net/http'

  def set_confirmed_by
    @order.confirmed_by = true
    @order.save
  end

  def order_to_string
    order_item_info = "Пиццы:\n"

    if !@order.order_items.empty?
      @order.order_items.each do |item|
        order_item_info << "#{item.pizza.name}:#{item.quantity}\n"
      end
    else
      ActiveModel::Error.new(Order, :order_to_string, :too_short, count: 1)
    end

    return order_item_info
  end

  def set_order_data_collection
    message = String.new("Информация о заказе: #{@order.id}\n")
    message << "-------------\n"
    message << "Имя: #{@order.name}\nТелефон: #{@order.phone}\n"
    message << "-------------\n"
    message << "Улица: #{@order.street}\n"
    message << "Номер дома: #{@order.house_number}\nНомер Подьезда:#{@order.subway_number}\n"
    message << "Номер квартиры:#{@order.apartament_number}\n"

    if !@order.note.empty?
      message << "Примечание: #{@order.note}\n"
    else
      message << "Примечания отсуствуют\n"
    end
    message << "-------------\n"

    message << "#{order_to_string}"
    message << "-------------\n"
    message << "За всё: #{@order.total} BYN"

    return message
  end

  def send_order_to_telegram
    message = set_order_data_collection
    chat_ids = Rails.configuration.chat_ids
    token = Rails.configuration.token
    # Если есть токен в переменной окружения отправить сообщение в телеграм-бот
    if token
      chat_ids.each do |chat_id|
        uri= URI("https://api.telegram.org/bot#{token}/sendMessage?")
        params = {:chat_id => chat_id, :parse_mode => 'html', :text => message}
        uri.query = URI.encode_www_form(params)
        Net::HTTP.get(uri)
      end
    end
  end

  def order_total
    current_order.save(validate: false)
    current_order.total
  end
end

app/views/carts/_cart_footer.html.erb
<button><%= link_to "Перейти в меню", menu_index_path %></button>
<% if session[:order_id] && (order_items_size > 0)  %>
  <button><%= link_to "Оформить заказ", edit_order_path(session[:order_id]) %></button>
<% end %>

app/views/carts/_cart_item.html.erb
<% if order_items_size > 0 %>
  <% cart_items.each do |item| %>
    <div class="cart-item">
      <button><%= link_to 'Удалить', item, method: :delete, remote: true %></button>
      <%= image_tag(item.pizza.photo, size: "90x90", alt: item.pizza.name) %>
      <%= item.pizza.name %>
      <br>
      <div class="sep"></div>
      <%= form_for(item, remote: true) do |f| %>
        <%= f.hidden_field :pizza_id, value: item.pizza.id %>
        <p>Количество</p>
        <%= f.number_field :quantity, value: item.quantity.to_i, min: 1 %>
        <%= f.submit "Обновить количество", style: "width: 160%; font-size: calc(6px + 16 * (100vw / 1920));"%>
      <% end %>
      Цена: <%= item.total_price %> BYN
    </div>
  <% end %>
  <p>Итого, епта: <%= order_total %> BYN </p>
<% else %>
  <p> Корзина пуста.</p>
<% end %>

app/views/carts/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'styles_delivery', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<section>
  <div class="cart">
    <div class="cart-headline">
          <p>Корзина</p>
    </div>

    <div class="cart-content">
        <div class="main-cart">
            <%= render 'cart_item' %>
        </div>
    </div>

    <div class="cart-footer">
      <%= render 'cart_footer' %>
    </div>

  </div>
</section>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FirePizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'styles_home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'logo_final.png'%>
</head>
<body>
<%= video_tag "ogon.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, id: "video" %>
<section>
  <div class="cont">
    <div class="content">
      <nav class="links">
        <div>
          <%= link_to "Меню", menu_index_path %>
        </div>
        <div>
          <%= link_to "Доставка", delivery_path %>
        </div>
      </nav>
      <div class="logo">
        <figure>
          <%= image_tag("logo_final.png", height: '31%', width: '31%')%>
        </figure>
      </div>
      <div class="text">
        <p>Попробуйте незабываемый огненный вкус!</p>
      </div>
      <div class="line"></div>
      <div class="contacts">
        <div><a href="https://www.instagram.com/fire_pizza_bus?r=nametag"><svg enable-background="new 0 0 24 24" height="54" viewBox="0 0 24 24" width="54" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="SVGID_1_" gradientTransform="matrix(0 -1.982 -1.844 0 -132.522 -51.077)" gradientUnits="userSpaceOnUse" x1="-37.106" x2="-26.555" y1="-72.705" y2="-84.047"><stop offset="0" stop-color="#fd5"/><stop offset=".5" stop-color="#ff543e"/><stop offset="1" stop-color="#c837ab"/></linearGradient><path d="m1.5 1.633c-1.886 1.959-1.5 4.04-1.5 10.362 0 5.25-.916 10.513 3.878 11.752 1.497.385 14.761.385 16.256-.002 1.996-.515 3.62-2.134 3.842-4.957.031-.394.031-13.185-.001-13.587-.236-3.007-2.087-4.74-4.526-5.091-.559-.081-.671-.105-3.539-.11-10.173.005-12.403-.448-14.41 1.633z" fill="url(#SVGID_1_)"/><path d="m11.998 3.139c-3.631 0-7.079-.323-8.396 3.057-.544 1.396-.465 3.209-.465 5.805 0 2.278-.073 4.419.465 5.804 1.314 3.382 4.79 3.058 8.394 3.058 3.477 0 7.062.362 8.395-3.058.545-1.41.465-3.196.465-5.804 0-3.462.191-5.697-1.488-7.375-1.7-1.7-3.999-1.487-7.374-1.487zm-.794 1.597c7.574-.012 8.538-.854 8.006 10.843-.189 4.137-3.339 3.683-7.211 3.683-7.06 0-7.263-.202-7.263-7.265 0-7.145.56-7.257 6.468-7.263zm5.524 1.471c-.587 0-1.063.476-1.063 1.063s.476 1.063 1.063 1.063 1.063-.476 1.063-1.063-.476-1.063-1.063-1.063zm-4.73 1.243c-2.513 0-4.55 2.038-4.55 4.551s2.037 4.55 4.55 4.55 4.549-2.037 4.549-4.55-2.036-4.551-4.549-4.551zm0 1.597c3.905 0 3.91 5.908 0 5.908-3.904 0-3.91-5.908 0-5.908z" fill="#fff"/></svg></a></div>
      </div>
      <div class="info">
        <figure>
          <%= image_tag("pay.png", height: '60%', width: '35%')%>
        </figure>
        <p>Зарегистрирован Минским горисполкомом 29 сентября 2020 г., рег. номер: 193472471</p>
        <p>Email: firepizzabus@gmail.com</p>
        <p>ул. Налибокская 36, ТЦ "Квадро"</p>
        <p>© 2021 Все права защищены.</p>
      </div>
    </div>
  </div>
</section>
</body>
</html>

app/views/layouts/_cart.html.erb
<div class="cart_link_div">
  <%= link_to "#{order_items_size} товаров в корзине, итоговая цена: #{order_total} BYN", carts_path, class: "cart_link" %>
</div>

app/views/layouts/_footer.html.erb
<section>
    <div class="footer">
        <div class="footer_icons">
            <div><a href="https://www.instagram.com/fire_pizza_bus"><svg enable-background="new 0 0 24 24" height="54" viewBox="0 0 24 24" width="54"
                    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <linearGradient id="SVGID_1_" gradientTransform="matrix(0 -1.982 -1.844 0 -132.522 -51.077)"
                        gradientUnits="userSpaceOnUse" x1="-37.106" x2="-26.555" y1="-72.705" y2="-84.047">
                        <stop offset="0" stop-color="#fd5" />
                        <stop offset=".5" stop-color="#ff543e" />
                        <stop offset="1" stop-color="#c837ab" />
                    </linearGradient>
                    <path
                        d="m1.5 1.633c-1.886 1.959-1.5 4.04-1.5 10.362 0 5.25-.916 10.513 3.878 11.752 1.497.385 14.761.385 16.256-.002 1.996-.515 3.62-2.134 3.842-4.957.031-.394.031-13.185-.001-13.587-.236-3.007-2.087-4.74-4.526-5.091-.559-.081-.671-.105-3.539-.11-10.173.005-12.403-.448-14.41 1.633z"
                        fill="url(#SVGID_1_)" />
                    <path
                        d="m11.998 3.139c-3.631 0-7.079-.323-8.396 3.057-.544 1.396-.465 3.209-.465 5.805 0 2.278-.073 4.419.465 5.804 1.314 3.382 4.79 3.058 8.394 3.058 3.477 0 7.062.362 8.395-3.058.545-1.41.465-3.196.465-5.804 0-3.462.191-5.697-1.488-7.375-1.7-1.7-3.999-1.487-7.374-1.487zm-.794 1.597c7.574-.012 8.538-.854 8.006 10.843-.189 4.137-3.339 3.683-7.211 3.683-7.06 0-7.263-.202-7.263-7.265 0-7.145.56-7.257 6.468-7.263zm5.524 1.471c-.587 0-1.063.476-1.063 1.063s.476 1.063 1.063 1.063 1.063-.476 1.063-1.063-.476-1.063-1.063-1.063zm-4.73 1.243c-2.513 0-4.55 2.038-4.55 4.551s2.037 4.55 4.55 4.55 4.549-2.037 4.549-4.55-2.036-4.551-4.549-4.551zm0 1.597c3.905 0 3.91 5.908 0 5.908-3.904 0-3.91-5.908 0-5.908z"
                        fill="#fff" />
                </svg></a></div>
        </div>
        <div class="footer_payment">
            <figure>
              <%= image_tag 'pay.png'%>
            </figure>
        </div>
    </div>
</section>

app/views/layouts/_messages.html.erb
<% if false %>
  <% flash.each do |name, msg| %>
      <div>
        <%= msg %>
        <button type="button" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirePizza</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'logo_final.png'%>
  </head>

  <body>
    <div class="content">
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
    <%= javascript_pack_tag 'scripts_menu' %>
  </body>
</html>

app/views/menu/_pizza.html.erb
<%
  row_count = (@pizzas.count/3.0).round
  all_full_row = row_count == (@pizzas.count/3.0) ? true : false
  iter = 1
%>

<% while iter <= row_count do %>

  <div class="line<%= iter%2 == 0 ? "" : "two" %>"></div>

  <div class="pizzas">
    <div class="pizza_row<%= (iter == row_count) && !all_full_row ? "_two" : ""%>">

      <% @pizzas.each do |pizza| %>
        <% if pizza.popularity == iter %>
          <div class="pizza_row_item <%= pizza.photo %>">
            <figure class="pizza_row_item_photo">
                <%= image_tag("#{pizza.photo}.png", class: "image") %>
            </figure>
            <div class="pizza_row_item_sub">
                <h1><%= pizza.name %></h1>
                <p>от <%= pizza.price %> руб.</p>
            </div>

            <div class="pizza_row_item_hovered_<%= pizza.photo %>">
                <div>
                    <figure class="pizza_row_item_photo">
                        <%= image_tag "#{pizza.photo}.jpg", class: "photo_exp" %>
                    </figure>
                </div>
                <div class="pizza_row_item_hovered_content">
                    <h1><%= pizza.name %></h1>
                    <p>(<%= pizza.ingredients %>)</p>
                    <h3><%= pizza.price %> руб, <%= pizza.weight %>г.</h3>
                    <div class="pizza_row_item_button_id<%= pizza.id %>">
                    <% if order_pizza_include?(pizza.id) %>
                      <p>Пицца в корзине!</p>
                    <% else %>
                      <%= form_for(@order_item, remote: true) do |f| %>
                        <%= f.hidden_field :pizza_id, value: pizza.id %>
                        <%= f.hidden_field :quantity, value: 1, min: 1%>
                        <%= f.submit "В корзину", class: 'submit_btn' %>
                      <% end %>
                    <% end %>
                    </div>
                </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% iter += 1 %>

<% end %>

app/views/menu/index.html.erb
<section>

  <div class="menu-headline">
      <p>Попробуйте неповторимый вкус пиццы на дровах!</p>
  </div>

      <%= render 'pizza' %>

  <div class="lineshort"></div>
</section>

app/views/order_items/create.js.erb
<% if current_order.errors.any? || @order_item.errors.any? %>
  alert('Invalid')
<% else %>
  $(".cart1").html("<%= escape_javascript(render 'layouts/cart') %>")
  $(".pizza_row_item_button_id<%= @order_item.pizza_id %>").html("<p>Пицца в корзине!</p>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart1").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".main-cart").html("<%= escape_javascript(render 'carts/cart_item') %>")
<% if order_items_size == 0 %>
  $(".cart-footer").html("<%= escape_javascript(render 'carts/cart_footer') %>")
<% end %>

app/views/order_items/update.js.erb
$(".cart1").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".main-cart").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/orders/_errors.html.erb
<% if @order.errors.any? %>

<div class="errors-div">
  <h2>Количество ошибок: <%= @order.errors.count %> </h2>
  <h4 class="alert-heading">Следующие ошибки не позволили сохранить заказ: </h4>
  <ul>
    <% @order.errors.each do |attribute, msg| %>
      <li style="list-style-type: circle"><%= msg %></li>
    <% end %>
  </ul>
</div>

<%end%>

app/views/orders/_form.html.erb
<section>
  <div class="delivery">
    <div class="delivery-headline">
            <p>Доставка</p>
    </div>

    <div class="delivery-content">
      <h1>Чтобы оформить Ваш заказ, заполните форму</h1>
      <%= render 'errors' %>
      <div class="delivery-content-form">
        <%= form_with(model: @order, local: true) do |f| %>
          <p>Имя: *</p>
          <%= f.text_field :name %>
          <p>Контактный телефон: *</p>
          <%= f.phone_field :phone, value: '+375' %>
          <br>
          <div class="delivery-content-form-minsk">
            <h1>Адрес доставки в Минске</h1>
            <p>Улица: *</p>
            <%= f.text_field :street %>
         
            <div class="delivery-content-form-minsk-homeaddress">
              <div>
                <p>Номер дома: *</p>
                <%= f.number_field :house_number, min: 1, max: 200 %>
              </div>
              <div class="l">
                <p>Номер корпуса:</p>
                <%= f.number_field :subway_number,  min: 1, max: 200 %>
              </div>
              <div class="l">
                <p>Номер квартиры:</p>
                <%= f.number_field :apartament_number, min: 1, max: 1000 %>
              </div>
            </div>
            <h2 class="delivery-content-form-minsk-homeaddress-note">Примечание (подъезд, этаж, доп. номер телефона):</h2>
            <%= f.text_field :note, style: "padding: 10px; margin-top: 30px;" %>
            <%= f.submit "Подтвердить заказ", class: "send-email", style: "margin-left: 15%; margin-top: 25px" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/orders/complete.html.erb
Заказ успешно сформирован

app/views/orders/edit.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'styles_delivery', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'errors', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<%= render 'form' %>

app/views/pizza/_pizza.html.erb
<% 
  row_count = (@pizzas.count/3.0).round
  all_full_row = row_count == (@pizzas.count/3.0) ? true : false
  iter = 1
%>

<% while iter <= row_count do %>
  
  <div class="line<%= iter%2 == 0 ? "" : "two" %>"></div>
  
  <div class="pizzas">
    <div class="pizza_row<%= (iter == row_count) && !all_full_row ? "_two" : ''%>">
 
      <% @pizzas.each do |pizza| %>
        <% if pizza.popularity == iter %>
          <div class="pizza_row_item <%= pizza.photo %>">
            <figure class="pizza_row_item_photo">
                <%= image_tag("#{pizza.photo}.png", class: "image") %>
            </figure>
            <div class="pizza_row_item_sub">
                <h1><%= pizza.name %></h1>
                <p>от <%= pizza.price %> руб.</p>
            </div>

            <div class="pizza_row_item_hovered_<%= pizza.photo %>">
                <div>
                    <figure class="pizza_row_item_photo">
                        <%= image_tag "#{pizza.photo}.jpg", class: "photo_exp" %>
                    </figure>
                </div>
                <div class="pizza_row_item_hovered_content">
                    <h1><%= pizza.name %></h1>
                    <p>(<%= pizza.ingredients %>)</p>
                    <h3><%= pizza.price %> руб, <%= pizza.weight %>г.</h3>
                    <button @click="addMargarita">В корзину</button>
                </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% iter += 1 %>

<% end %>  

app/views/pizzas/_form.html.erb
<%= form_with(model: @pizza, local: true) do |f| %>
  <div>
    <%= f.label :name%>
    <div>
      <%= f.text_field :name, placeholder: "Введите название пиццы" %>
    </div>
  </div>

  <div>
    <%= f.label :price%>
    <div>
      <%= f.text_field :price, placeholder: "Введите цену пиццы" %>
    </div>
  </div>

  <div>
    <%= f.label :ingredients%>
    <div>
      <%= f.text_field :ingredients, placeholder: "Введите ингредиенты" %>
    </div>
  </div>

  <div>
    <%= f.label :description%>
    <div>
      <%= f.text_field :description, placeholder: "Введите описание" %>
    </div>
  </div>

  <div>
    <%= f.label :weight%>
    <div>
      <%= f.text_field :weight, placeholder: "Введите вес" %>
    </div>
  </div>

  <div>
    <%= f.label :photo%>
    <div>
      <%= f.text_field :photo, placeholder: "Введите название фото" %>
    </div>
  </div>

  <div>
    <%= f.label :popularity%>
    <div>
      <%= f.number_field :popularity, placeholder: "Введите коэф. популярности" %>
    </div>
  </div>

  <div>
    <%= f.submit(@pizza.new_record? ? "Создать пиццу" : "обновить пиццу") %>
  </div>
<% end %>

app/views/pizzas/delivery.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'styles_delivery', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>
<section>
  <div class="cart">
    <div class="cart-headline">
          <p>Доставка</p>
    </div>
  
    <div class="cart-content">
        <p>Доставка осуществляется на территории Минска.</p>
    </div>

    <a href="https://yandex.ru/maps/?um=constructor%3Abe60a6550dce1fafc257d08f233de69fec5cdc52d16233341b7bc4b1ce01bc60&amp;source=constructorStatic" target="_blank"><img src="https://api-maps.yandex.ru/services/constructor/1.0/static/?um=constructor%3Abe60a6550dce1fafc257d08f233de69fec5cdc52d16233341b7bc4b1ce01bc60&amp;width=500&amp;height=400&amp;lang=ru_RU" alt="" style="border: 0;" /></a>

    <div class="cart-footer">
    <button><%= link_to "Перейти в меню", menu_index_path %></button>
    </div>
  </div>
</section>

app/views/pizzas/edit.html.erb
<section>

  <div class="menu-headline">
      <p>Описание pizzы</p>
  </div>

      <%= render 'form' %>

</section>